#@author    Salman Omar Sohail <support@mybotshop.de>
#@copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.

/**:
  b2_webserver:
    ros__parameters:
      robot_map_topic: "map"
      robot_cmd_vel: "webserver/cmd_vel"
      robot_e_stop: "e_stop"
      robot_gps_lat: 50.9533
      robot_gps_lon: 6.60266
      robot_password: "Unitree0408"
      robot_gps_topic: "drotek/ublox_gps_node/fix"
      robot_battery_topic: "sensor/battery/state"
      robot_webserver: "b2-webserver"
      robot_max_linear_velocity: 0.1
      robot_max_angular_velocity: 0.1
      robot_rosbag_dir: "/opt/mybotshop/bags/"
      robot_rosbag_storage: 1000000000
      robot_rosbag_duration: 1800
      robot_services:
        [
        "b2-nano",
        # "b2-drotek",
        "b2-pcd-scan",
        "b2-twistmux",
        "b2-hardware",
        "b2-webserver", 
        "b2-rear-video",
        "b2-front-video",
        "b2-description",
        "b2-livox-mid360",
        "b2-statepublisher",
        "b2-realsense-d405",
        "b2-domain-bridge",
      ]
      web_security: true
      web_user: "admin"
      web_password: "mybotshop"
      web_server_ip: "0.0.0.0"
      web_server_port: 9000
