#!/bin/sh

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

REDDDD='\033[0;31m'
ORANGE='\033[0;33m'
DGREEN='\033[0;32m'
GREENN='\033[1;32m'
LGREEN='\033[0;32m'
WHITEE='\033[0;37m'
BLUEEE='\033[1;34m'
CYANNN='\033[0;96m'
YELLOW='\033[1;33m'
YEELOW='\033[0;93m'
PURPLE='\033[0;35m'
NCCCCC='\033[0m'

# neofetch
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"       _  _  _  _  ____   __  ____  ____  _  _   __  ____                      "${WHITEE}
echo ${GREENN}"      ( \/ )( \/ )(  _ \ /  \(_  _)/ ___)/ )( \ /  \(  _ \                     "${WHITEE}
echo ${GREENN}"      / \/ \ )  /  ) _ ((  O ) )(  \___ \) __ ((  O )) __/                     "${WHITEE}
echo ${GREENN}"      \_)(_/(__/  (____/ \__/ (__) (____/\_)(_/ \__/(__)                       "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Network                                                                        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${ORANGE}"Name                 "${ORANGE}"IP Address                   Username  Password    "${WHITEE}
echo ${YEELOW}"-------------------  "${YEELOW}"-------------                --------- ------------"${WHITEE}
echo ${YEELOW}"B2 MCU               "${WHITEE}"192.168.123.161              -         -           "${WHITEE}
echo ${YEELOW}"B2 PC4               "${WHITEE}"192.168.123.164              -         Unitree0408 "${WHITEE}
echo ${YEELOW}"B2 PC4 Webserver     "${WHITEE}"http://192.168.123.164:9000  -         mybotshop   "${WHITEE}
echo ${YEELOW}"B2 Robosense Lidar   "${WHITEE}"192.168.123.162              -         -           "${WHITEE}
echo ${YEELOW}"B2 Livoxmid360 Lidar "${WHITEE}"192.168.123.162              -         -           "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${GREENN}"Drivers                                                                        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${YEELOW}"Teleoperation:       "${CYANNN}"ros2 run teleop_twist_keyboard teleop_twist_keyboard"${WHITEE}
echo ${YEELOW}"                                                                               "${WHITEE}
echo ${YEELOW}"Navi SLAM:           "${CYANNN}"ros2 launch b2_nav2 slam.launch.py             "${WHITEE}
echo ${YEELOW}"Navi Map:            "${CYANNN}"ros2 launch b2_nav2 map_navi.launch.py         "${WHITEE}
echo ${YEELOW}"Navi Odom:           "${CYANNN}"ros2 launch b2_nav2 odom_navi.launch.py        "${WHITEE}
echo ${YEELOW}"                                                                               "${WHITEE}
echo ${YEELOW}"Visualization:       "${CYANNN}"ros2 launch b2_viz view_robot.launch.py        "${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}
echo ${PURPLEE}"https://www.docs.quadruped.de/projects/b2/html/index.html"${WHITEE}
echo ${DGREEN}"-------------------------------------------------------------------------------"${WHITEE}