controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_effort_controller:
      # type: effort_controllers/JointGroupEffortController
      type: joint_trajectory_controller/JointTrajectoryController


    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - FL_foot_fixed
      - FR_foot_fixed
      - RL_foot_fixed
      - RR_foot_fixed
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_effort_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      FL_hip_joint      : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      FL_thigh_joint    : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      FL_calf_joint     : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      FR_hip_joint      : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      FR_thigh_joint    : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      FR_calf_joint     : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RL_hip_joint      : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RL_thigh_joint    : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RL_calf_joint     : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RR_hip_joint      : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RR_thigh_joint    : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}
      RR_calf_joint     : {p: 200.0, i: 0.0, d: 4.0, i_clamp: 2.5}

joint_position_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
    command_interfaces:
      # - position
      - effort
    state_interfaces:
      - position
      - velocity

    gains:
      FL_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FL_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FL_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }

joint_trajectory_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    gains:
      FL_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FL_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FL_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      FR_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RL_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_hip_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_thigh_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }
      RR_calf_joint:
        { p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5, ff_velocity_scale: 1.0 }