#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Software License Agreement (BSD)
#
# @author    Salman Omar Sohail <support@mybotshop.de>
# @copyright (c) 2025, MYBOTSHOP GmbH, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, is not permitted without the express permission
# of MYBOTSHOP GmbH.


import rclpy
from b2_vision_action.librosnode import Ros2Vision


def launch_webserver(args=None):

    rclpy.init(args=args)
    rv = Ros2Vision()

    try:
        rclpy.spin(rv)
    except KeyboardInterrupt:
        pass
    finally:
        rv.destroy_node()

if __name__ == '__main__':
    launch_webserver()
