name: b2_366_domain_bridge
from_domain: 0
to_domain: 10
topics:
  /odommodestate:
    type: unitree_go/msg/SportModeState
    remap: b2_366/odommodestate
  /lf/lowstate:
    type: unitree_go/msg/LowState
    remap: b2_366/lf/lowstate
